# Audio bell is just unbearable
enable_audio_bell no

#enabled_layouts Grid,Stack,Splits  # Splits seems powerful, but a bit too much for what I do with it, making it needlessly complex
enabled_layouts Grid,Stack
tab_bar_style powerline
tab_bar_edge top

map super+tab next_tab
map super+shift+tab previous_tab

map ctrl+tab next_window
map ctrl+shift+tab previous_window

map ctrl+shift+T new_tab_with_cwd
map ctrl+shift+enter new_window_with_cwd

map ctrl+shift+D detach_window


#    FiraCode Nerd Font Mono Bold (FiraCodeNFM-Bold)
#    FiraCode Nerd Font Mono Light (FiraCodeNFM-Light)
#    FiraCode Nerd Font Mono Med (FiraCodeNFM-Med)
#    FiraCode Nerd Font Mono Reg (FiraCodeNFM-Reg)
#    FiraCode Nerd Font Mono Ret (FiraCodeNFM-Ret)
#    FiraCode Nerd Font Mono SemBd (FiraCodeNFM-SemBd)

# font_family      FiraCodeNFM
# bold_font        FiraCodeNFM-SemBd
# italic_font      FiraCodeNFM-Med

font_family      HackNFM
bold_font        HackNFM-Bold
italic_font      HackNFM-Italic

cursor_blink_interval 0
cursor_shape block
shell_integration no-cursor

scrollback_lines 10000
scrollback_pager_history_size 1000

notify_on_cmd_finish never

open_url_modifiers ctrl
